# configuration nginx
---
- name: Creer le repertoire d'installation
  file:
    path: "{{ httpd_path }}"
    state: directory 
    owner: root
    group: root
    mode: '0755'

- name: Copy nginx.conf on the client server
  template:
    src: nginx.conf.j2
    dest: "{{ httpd_dir }}/nginx.conf"
    owner: root
    group: root
    mode: '0644'

- name: Copy Dockefile on the client server
  template:
    src: Dockerfile.j2
    dest: "{{ httpd_dir }}/Dockerfile"
    owner: root
    group: root
    mode: '0644'

- name: Build Nginx image
  docker_image:
    name: "{{ httpd_image }}"
    build: 
      path: "{{ httpd_dir }}"
    source: build
    state: present

- name: Run Nginx container
  docker_container:
    name: "{{ httpd_name }}"
    image: "{{ httpd_image }}"
    state: started
    restart: yes
    networks:
       - name: "{{ network_name }}"
    ports:
       - "80:80"
       - "443:443"
...  
